<?php

namespace core\item\items;

use pocketmine\item\EnderPearl as PMEnderPearl;
use pocketmine\math\Vector3;
use pocketmine\Player;

class EnderPearl extends PMEnderPearl {

    public function getThrowForce() : float {
        return 2;
    }

    public function onClickAir(Player $player, Vector3 $directionVector) : bool {
        return parent::onClickAir($player, $directionVector); // TODO: Change the autogenerated stub
    }
}